version: "3.8"

# Services definition
services:
  # Main weather service
  weather-service:
    build:
      context: .
      dockerfile: Dockerfile

    # Container name for easier reference
    container_name: weather-classification-api

    # Port mapping: host:container
    ports:
      - "8080:8080"

    # Environment variables
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - HOST=0.0.0.0
      - PORT=8080

    # Volume mounts for development
    # Mounts local .env file into container so changes are reflected
    volumes:
      - ./.env:/app/.env:ro # :ro means read-only

    # Restart policy
    # unless-stopped: restart unless explicitly stopped
    restart: unless-stopped

    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: weather_service
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:
