name: Build, Lint and Test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  setup:
    name: ⚙️ Setup and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚡️ Install dependencies
        uses: ./.github/actions/setup-install-dependencies
        with:
          python-version: "3.13"
          requirements-files: "requirements-dev.txt"

  compile:
    name: 🏗️ Validate Python Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚡️ Setup dependencies
        uses: ./.github/actions/setup-install-dependencies
        with:
          python-version: "3.13"
          requirements-files: "requirements-dev.txt"

      - name: 🏗️ Compile Python files
        run: |
          python -m py_compile $(git ls-files '*.py')
          echo "✅ All Python files compile successfully"

  lint:
    name: 🔎 Lint with Pylint
    runs-on: ubuntu-latest
    needs: setup
    # TODO: Remove once linting issues fixed
    continue-on-error: true

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚡️ Setup dependencies
        uses: ./.github/actions/setup-install-dependencies
        with:
          python-version: "3.13"
          requirements-files: "requirements-dev.txt"

      - name: 🔎 Run Pylint
        run: |
          python -m pylint $(git ls-files '*.py')

  test:
    name: 🧪 Test with Pytest
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚡️ Setup dependencies
        uses: ./.github/actions/setup-install-dependencies
        with:
          python-version: "3.13"
          requirements-files: "requirements-dev.txt"

      - name: 🧪 Run Pytest
        run: |
          python -m pytest --pyargs pylint_pydantic --cov-report term --cov-report xml:coverage.xml tests/
