name: Plan and Deploy Infrastructure

on:
  workflow_dispatch

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.0

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      ecr-repository: ${{ steps.tf-output.outputs.ecr-repository }}
      lambda-function-name: ${{ steps.tf-output.outputs.lambda-function-name }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./infrastructure
      run: terraform init

    - name: Terraform Plan
      working-directory: ./infrastructure
      run: terraform plan -no-color

    - name: Terraform Apply
      working-directory: ./infrastructure
      run: terraform apply -auto-approve

    - name: Get Terraform Outputs
      id: tf-output
      working-directory: ./infrastructure
      run: |
        echo "ecr-repository=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT
        echo "lambda-function-name=$(terraform output -raw lambda_function_name)" >> $GITHUB_OUTPUT