name: Infrastructure - Plan

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.0

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./infrastructure
      run: terraform init

    - name: Terraform Plan
      working-directory: ./infrastructure
      run: terraform plan -no-color
      continue-on-error: true